name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        
    - name: Install Hype framework
      run: |
        git clone https://github.com/twilson63/hype.git /tmp/hype
        cd /tmp/hype
        go build -o hype
        sudo cp hype /usr/local/bin/hype
        sudo chmod +x /usr/local/bin/hype
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip
        
    - name: Set version
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi
        
    - name: Make build script executable
      run: chmod +x build-release.sh
        
    - name: Create release binaries
      run: |
        ./build-release.sh ${{ steps.version.outputs.VERSION }}
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: fs-explore ${{ steps.version.outputs.VERSION }}
        body: |
          ## fs-explore ${{ steps.version.outputs.VERSION }}
          
          Cross-platform TUI file explorer with syntax highlighting.
          
          ### Installation
          
          **Quick install (Linux/macOS):**
          ```bash
          curl -fsSL https://raw.githubusercontent.com/twilson63/fs-explore/main/install.sh | bash
          ```
          
          **Windows:**
          🚧 Windows support coming soon! Use WSL with the Linux method above.
          
          **Manual install:**
          Download the appropriate binary for your platform below.
          
          ### Features
          - 📁 Cross-platform file navigation
          - 🎨 Syntax highlighting for 6+ languages
          - ⌨️ Vim-inspired keyboard shortcuts
          - 🔍 Binary file detection
          
          ### Supported Platforms
          - Linux (x86_64, ARM64)
          - macOS (Intel, Apple Silicon)
          - Windows (coming soon!)
          
          ### Checksums
          See `checksums.txt` for file verification.
        draft: false
        prerelease: false
        files: |
          dist/fs-explore-linux-amd64.tar.gz
          dist/fs-explore-linux-arm64.tar.gz
          dist/fs-explore-darwin-amd64.tar.gz
          dist/fs-explore-darwin-arm64.tar.gz
          dist/checksums.txt
          dist/README.txt
